#!/usr/bin/env bash

set -e -u -x

# Clean files that may be left over if container doesn't shut down cleanly.
rm -f /tmp/.s.PGSQL.*

# Clean files that are tailed by fluent-bit when using console output to prevent
# lots of output from previous logs on startup.
rm -f /var/log/api-umbrella/trafficserver/error.log

make
api-umbrella run
