#!/usr/bin/env bash

set -e -u -x

mkdir -p /etc/api-umbrella
{
  echo "app_env: development"
  echo "http_port: $HTTP_PORT"
  echo "https_port: $HTTPS_PORT"
} > /etc/api-umbrella/api-umbrella.yml

ln -snf /build/build/work/stage/opt/api-umbrella /opt/api-umbrella
ln -snf /build/build/work/stage/opt/api-umbrella/var/log /var/log/api-umbrella
ln -snf /build/build/work ./build/work
ln -snf /build/CMakeFiles ./CMakeFiles
ln -snf /build/CMakeCache.txt ./CMakeCache.txt
ln -snf /build/Makefile ./Makefile
mkdir -p /build/test/tmp/run
mkdir -p ./test/tmp
ln -snf /build/test/tmp/run ./test/tmp/run

(cd /build && env PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" make)

chmod 1777 /app/src/api-umbrella/admin-ui/tmp

api-umbrella run
