#!/usr/bin/env bash

set -e -u -x

export PATH="/app/bin:/build/build/work/dev-env/sbin:/build/build/work/dev-env/bin:/build/build/work/test-env/sbin:/build/build/work/test-env/bin:/build/build/work/stage/opt/api-umbrella/sbin:/build/build/work/stage/opt/api-umbrella/bin:/build/build/work/stage/opt/api-umbrella/embedded/sbin:/build/build/work/stage/opt/api-umbrella/embedded/bin:${PATH}"
export API_UMBRELLA_ROOT="/build/build/work/stage/opt/api-umbrella"

mkdir -p /etc/api-umbrella
{
  echo "app_env: development"
  echo "http_port: $HTTP_PORT"
  echo "https_port: $HTTPS_PORT"
  echo "log:"
  echo "  destination: console"
  echo "postgresql:"
  echo "  password: password"
  echo "  migrations:"
  echo "    password: password"
  echo "  auto_ssl:"
  echo "    password: password"
  echo "  embedded_server_config:"
  echo "    listen_addresses: 0.0.0.0"
} > /etc/api-umbrella/api-umbrella.yml

mkdir -p /build/.task
ln -snf /build/.task /app/.task

mkdir -p /build/build/work/stage/opt/api-umbrella/var/log
ln -snf /build/build/work/stage/opt/api-umbrella /opt/api-umbrella
ln -snf /build/build/work/stage/opt/api-umbrella/var/log /var/log/api-umbrella
ln -snf /build/build/work /app/build/work

mkdir -p /build/test/tmp/run
mkdir -p /app/test/tmp
ln -snf /build/test/tmp/run /app/test/tmp/run

mkdir -p /app/build/work/tasks/app-deps/admin-ui/yarn/_persist/node_modules
ln -snf /app/build/work/tasks/app-deps/admin-ui/yarn/_persist/node_modules /app/src/api-umbrella/admin-ui/node_modules

mkdir -p /app/build/work/tasks/app-deps/web-app/yarn/_persist/node_modules
ln -snf /app/build/work/tasks/app-deps/web-app/yarn/_persist/node_modules /app/src/api-umbrella/web-app/node_modules

mkdir -p /app/build/work/tasks/test-deps/bundle/_persist/.bundle
ln -snf /app/build/work/tasks/test-deps/bundle/_persist/.bundle /app/.bundle

mkdir -p /app/src/api-umbrella/admin-ui/tmp
chmod 1777 /app/src/api-umbrella/admin-ui/tmp

exec "$@"
