#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

task_working_dir

# Install into the task's special _persist directory so the large node_modules
# directory isn't cleaned between runs for development purposes.
mkdir -p _persist
cd _persist

# Copy the npm/pnpm config files into the working directory and perform the
# installation here (so we're not creating/modifying files in the source
# directory).
cp "$SOURCE_DIR/src/api-umbrella/admin-ui/package.json" ./
cp "$SOURCE_DIR/src/api-umbrella/admin-ui/pnpm-lock.yaml" ./
PATH="$DEV_PATH" pnpm install --frozen-lockfile

# Remove some unnecessary and large files that are shipped in a couple of the
# Ember npm packages (I think usually by accident). This just helps slim down
# the size of node_modules a bit.
rm -rf ./node_modules/*/.node_modules.ember-try

stamp
