#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

task_working_dir

# Install into the task's special _persist directory so the large node_modules
# directory isn't cleaned between runs for development purposes.
mkdir -p _persist
cd _persist

# Copy the npm/yarn config files into the working directory and perform the
# installation here (so we're not creating/modifying files in the source
# directory).
cp $SOURCE_DIR/src/api-umbrella/admin-ui/package.json ./
cp $SOURCE_DIR/src/api-umbrella/admin-ui/yarn.lock ./
PATH="$DEV_INSTALL_PREFIX/bin:$DEFAULT_PATH" yarn install --frozen-lockfile

# In the CI environment, the "node-sass/vendor" directory seems to sometimes
# go away. A bit of a hack, but try to workaround this by forcing node-sass
# to be reinstalled if the vendor dir is missing.
#
# See:
# https://github.com/yarnpkg/yarn/issues/1981
# https://github.com/yarnpkg/yarn/issues/1832
# https://github.com/sass/node-sass/issues/1579
test -d node_modules/node-sass && test -d node_modules/node-sass/vendor || env PATH="$DEV_INSTALL_PREFIX/bin:$DEFAULT_PATH" yarn add node-sass --force

stamp
