source "https://rubygems.org"

gem "rake", "~> 11.3.0"

# Tests
gem "minitest", "~> 5.9.0"

# More test outputs
gem "minitest-reporters", "~> 1.1.11"

# For an "after_all" callback.
gem "minitest-hooks", "~> 1.4.0"

# Running background processes
gem "childprocess", "~> 0.5.9"

# Making HTTP requests
gem "typhoeus", "~> 1.1.0"

# JSON parsing
gem "multi_json", "~> 1.12.1"
gem "oj", "~> 2.17.5"

# Database libraries
gem "mongoid", "~> 6.0.2"
gem "elasticsearch", "~> 2.0.0"
gem "elasticsearch-persistence", "~> 0.1.9"

# Factories for test database data
gem "factory_girl", "~> 4.7.0"

gem "database_cleaner", "~> 1.5.3"

gem "rails_compatible_cookies_utils", "~> 0.1.0"

# Localization tests
gem "i18n", "~> 0.7.0"

# URL parsing/generation
gem "addressable", "~> 2.4.0"

# Browser/JavaScript integration tests
gem "capybara", "~> 2.10.1"
gem "minitest-capybara", "~> 0.8.2"

# Webkit-based driver for capybara
gem "poltergeist", "~> 1.11.0"

# Take screenshots on capybara test failures
gem "capybara-screenshot", "~> 1.0.14"

# Useful additions
gem "activesupport", "~> 5.0.0"

# Path-based setting of hashes
gem "lazyhash", "~> 0.1.1"

# Generating fake strings and data.
gem "faker", "~> 1.6.6"

# Debug printing
gem "awesome_print", "~> 1.7.0"
