#!/usr/bin/env bash

lua_lrexlib_pcre_version="2.9.1-1"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

# Install a patched version of lrexlib-pcre that is linked to luajit-5.1 so
# that this works in Trafficserver, where more explicit linking is required:
# https://github.com/apache/trafficserver/issues/5158
"${LUAROCKS_CMD[@]}" --tree="$APP_CORE_VENDOR_LUA_DIR" install "$SOURCE_DIR/tasks/app-deps/lua/lrexlib-pcre-$lua_lrexlib_pcre_version.rockspec" "${LUAROCKS_VARS[@]}" STAGE_EMBEDDED_LIBDIR="$STAGE_EMBEDDED_DIR/openresty/luajit/lib"
chrpath -d "$APP_CORE_VENDOR_LUA_DIR/lib/lua/5.1/rex_pcre.so"

stamp
