#!/usr/bin/env bash

lua_luasocket_version="4df569e9f867432f25f0bfbfa56b0962feb3326e"
lua_luasocket_hash="8e95251f3aec7dc5bd732c78bb25192b"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://github.com/diegonehab/luasocket/archive/$lua_luasocket_version.tar.gz" "md5" "$lua_luasocket_hash"
extract_download "$lua_luasocket_version.tar.gz"

# Just install the URL parsing library from luasocket (rather than the whole
# luarocks, since we don't need the other parts, and the luarock is somewhat
# outdated). In order to just install this one file, patch it to work without
# the base luasocket library present (it doesn't actually use the base stuff
# for anything).
cd "luasocket-$lua_luasocket_version"
sed -i -e "s%local socket = require.*%local socket = {}%" src/url.lua
install -D -m 644 src/url.lua "$VENDOR_LUA_DIR/socket/url.lua"
