#!/usr/bin/env bash

lua_luasocket_version="288219fd6b53ce2e709745c9918aa4c4b7f715c9"
lua_luasocket_hash="8dfe5d11178cc9279fc94f72eeb05dfc"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://github.com/diegonehab/luasocket/archive/$lua_luasocket_version.tar.gz" "md5" "$lua_luasocket_hash"
extract_download "$lua_luasocket_version.tar.gz"

# Just install the URL parsing library from luasocket (rather than the whole
# luarocks, since we don't need the other parts, and the luarock is somewhat
# outdated). In order to just install this one file, patch it to work without
# the base luasocket library present (it doesn't actually use the base stuff
# for anything).
cd "luasocket-$lua_luasocket_version"
sed -i -e "s%local socket = require.*%local socket = {}%" src/url.lua
install -D -m 644 src/url.lua "$APP_CORE_VENDOR_LUA_SHARE_DIR/socket/url.lua"

stamp
