#!/usr/bin/env bash

lua_mongo_version="1.2.1-1"

set -e -u -x
source ./tasks/helpers.sh

"${LUAROCKS_CMD[@]}" --tree="$APP_CORE_VENDOR_LUA_DIR" install "lua-mongo" "$lua_mongo_version" LIBBSON_DIR="$STAGE_EMBEDDED_DIR" LIBMONGOC_DIR="$STAGE_EMBEDDED_DIR"
find "$APP_CORE_VENDOR_LUA_DIR/lib" -name "mongo.so" -exec chrpath -d {} \;

stamp
