#!/usr/bin/env bash

lua_psl_version="0.3-0"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh
source ./tasks/helpers/detect_os_release.sh

detect_os_release
extra_args=()
if [[ "$ID_NORMALIZED" == "rhel" && "$VERSION_ID" == "7" ]]; then
  extra_args=("PSL_DIR=$STAGE_EMBEDDED_DIR")
fi

luarocks_install "psl" "$lua_psl_version" "${extra_args[@]}"

stamp
