#!/usr/bin/env bash

lua_psl_version="0.3-0"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

extra_args=("PSL_DIR=$STAGE_EMBEDDED_DIR")
luarocks_install "psl" "$lua_psl_version" "${extra_args[@]}"

stamp
