#!/usr/bin/env bash

lua_resty_radixtree_version="2.8.2-0"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

luarocks_install "lua-resty-radixtree" "$lua_resty_radixtree_version"

stamp
