#!/usr/bin/env bash

lua_cbson_version="3dc85e5a2b78829fa70beeb320037052b086d0e8"
lua_cbson_hash="556670f8540cbaf93c66660740e131d0"

lua_resty_moongoo_version="acedcad2dc7cd049cd50bd8aa32cbc31d8670564"
lua_resty_moongoo_hash="6924fade8de3ad2ea950cf680d951275"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir

# lua-cbson dependency
download "https://github.com/isage/lua-cbson/archive/$lua_cbson_version.tar.gz" "md5" "$lua_cbson_hash"
extract_download "$lua_cbson_version.tar.gz"
cd "lua-cbson-$lua_cbson_version"
mkdir cmake-build
cd cmake-build
LUA_DIR="$STAGE_EMBEDDED_DIR/openresty/luajit" CMAKE_PREFIX_PATH="$STAGE_EMBEDDED_DIR" cmake ..
make -j"$NPROC"
chrpath -d cbson.so
install -D -m 644 cbson.so "$APP_CORE_VENDOR_LUA_DIR/lib/lua/5.1/cbson.so"

# lua-resty-moongoo
download "https://github.com/isage/lua-resty-moongoo/archive/$lua_resty_moongoo_version.tar.gz" "md5" "$lua_resty_moongoo_hash"
extract_download "$lua_resty_moongoo_version.tar.gz"
cd "lua-resty-moongoo-$lua_resty_moongoo_version"
mkdir -p "$APP_CORE_VENDOR_LUA_SHARE_DIR/resty/moongoo"
rsync -a -v --checksum --delete-after ./lib/resty/moongoo.lua "$APP_CORE_VENDOR_LUA_SHARE_DIR/resty/moongoo.lua"
rsync -a -v --checksum --delete-after ./lib/resty/moongoo/ "$APP_CORE_VENDOR_LUA_SHARE_DIR/resty/moongoo/"

stamp
