#!/usr/bin/env bash

lua_resty_http_version="0.13"

set -e -u -x
source ./tasks/helpers.sh

# Clean old version to deal with rename from "pintsized/lua-resty-http" (v0.12)
# to "ledgetech/lua-resty-http" (v0.13).
rm -rf "$APP_CORE_VENDOR_LUA_DIR/resty_modules/pod/lua-resty-http-"* rm -rf "$APP_CORE_VENDOR_LUA_DIR/resty_modules/manifest/lua-resty-http."*

opm_install "ledgetech/lua-resty-http" "$lua_resty_http_version"

stamp
