#!/usr/bin/env bash

lua_resty_mlcache_version="2.4.1"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

opm_install "thibaultcha/lua-resty-mlcache" "$lua_resty_mlcache_version"

stamp
