#!/usr/bin/env bash

lua_resty_shcache_version="fb2e275c2cdca08eaa34a7b73375e41ac3eff200"
lua_resty_shcache_hash="5d3cbcf8fbad1954cdcb3826afa41afe"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://github.com/cloudflare/lua-resty-shcache/archive/$lua_resty_shcache_version.tar.gz" "md5" "$lua_resty_shcache_hash"
extract_download "$lua_resty_shcache_version.tar.gz"

install -D -m 644 "lua-resty-shcache-$lua_resty_shcache_version/shcache.lua" "$APP_CORE_VENDOR_LUA_SHARE_DIR/shcache.lua"

stamp
