#!/usr/bin/env bash

lua_resty_session_version="3.10"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

opm_install "bungle/lua-resty-session" "$lua_resty_session_version"

stamp
