#!/usr/bin/env bash

lua_resty_validation_version="2.7"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

opm_install "bungle/lua-resty-validation" "$lua_resty_validation_version"

stamp
