#!/usr/bin/env bash

lua_resty_logger_socket_version="15cc1c256e55b8e68ec9b220b6883c227a763d4e"
lua_resty_logger_socket_hash="efe14697a8c4be612c011f54fce06191"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://github.com/cloudflare/lua-resty-logger-socket/archive/$lua_resty_logger_socket_version.tar.gz" "md5" "$lua_resty_logger_socket_hash"
extract_download "$lua_resty_logger_socket_version.tar.gz"

install -D -m 644 "lua-resty-logger-socket-$lua_resty_logger_socket_version/lib/resty/logger/socket.lua" "$APP_CORE_VENDOR_LUA_SHARE_DIR/resty/logger/socket.lua"

stamp
