AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*

Rails:
  Enabled: true

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Lint/LiteralInInterpolation:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/SpaceAroundKeyword:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    find: 'detect'

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Exclude:
    - db/migrate/**
