site :opscode

cookbook "ack", :github => "NREL-cookbooks/ack"
cookbook "acl", :github => "NREL-cookbooks/acl"
cookbook "api-umbrella", :github => "NREL-cookbooks/api-umbrella"
cookbook "bundler", :github => "NREL-cookbooks/bundler"
cookbook "chef-client", "~> 3.2.0"
cookbook "envbuilder", :github => "theodi/chef-envbuilder"
cookbook "etc", :github => "NREL-cookbooks/etc"
cookbook "fail2ban", "~> 2.1.2"
cookbook "geoip", :github => "NREL-cookbooks/geoip"
cookbook "iptables", :github => "NREL-cookbooks/iptables"
cookbook "mongodb", :github => "NREL-cookbooks/mongodb"
cookbook "nano", "~> 1.0.0"
cookbook "nginx", :github => "NREL-cookbooks/nginx", :branch => "api-umbrella"
cookbook "nodejs", :github => "NREL-cookbooks/nodejs"
cookbook "openssh", "~> 1.3.2"
cookbook "omnibus_updater", "~> 0.2.8"
cookbook "pygments", :github => "NREL-cookbooks/pygments"
cookbook "rbenv", :github => "NREL-cookbooks/rbenv"
cookbook "redis", :github => "NREL-cookbooks/redis"
cookbook "rubygems", :github => "NREL-cookbooks/rubygems"
cookbook "screen", "~> 0.8.0"
cookbook "shasum", :github => "NREL-cookbooks/shasum"
cookbook "sudo", :github => "NREL-cookbooks/sudo"
cookbook "supervisor", :github => "NREL-cookbooks/supervisor"
cookbook "vagrant_extras", :github => "NREL-cookbooks/vagrant_extras"
cookbook "varnish", :github => "NREL-cookbooks/varnish"
cookbook "vim", "~> 1.1.2"
cookbook "yum", :github => "NREL-cookbooks/yum"
cookbook "zsh", "~> 1.0.0"
