FROM debian:jessie

RUN mkdir /app
COPY build/scripts/install_build_dependencies /app/build/scripts/install_build_dependencies
COPY build/package_dependencies.sh /app/build/package_dependencies.sh
RUN env INSTALL_TEST_DEPENDENCIES=true /app/build/scripts/install_build_dependencies

RUN mkdir /build
WORKDIR /build

COPY build/scripts/download_cmake /app/build/scripts/download_cmake
RUN /app/build/scripts/download_cmake

COPY CMakeLists.txt /app/CMakeLists.txt
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
COPY build/cmake /app/build/cmake
COPY config/default.yml /app/config/default.yml
COPY configure /app/configure
COPY src/api-umbrella/admin-ui /app/src/api-umbrella/admin-ui
COPY src/api-umbrella/version.txt /app/src/api-umbrella/version.txt
COPY src/api-umbrella/web-app /app/src/api-umbrella/web-app
RUN /app/configure --enable-test-dependencies && make

RUN groupadd -r api-umbrella && \
  useradd -r -g api-umbrella -s /sbin/nologin -d /opt/api-umbrella -c "API Umbrella user" api-umbrella

COPY . /app

ENV PATH="/app/bin:/build/build/work/dev-env/sbin:/build/build/work/dev-env/bin:/build/build/work/test-env/sbin:/build/build/work/test-env/bin:/build/build/work/stage/opt/api-umbrella/sbin:/build/build/work/stage/opt/api-umbrella/bin:/build/build/work/stage/opt/api-umbrella/embedded/sbin:/build/build/work/stage/opt/api-umbrella/embedded/bin:${PATH}"
ENV API_UMBRELLA_ROOT="/build/build/work/stage/opt/api-umbrella"

WORKDIR /app
CMD ./docker/dev/docker-start
