FROM ubuntu:16.04 AS build

RUN mkdir -p /app/build /build/build/work
RUN ln -snf /build/.task /app/.task
RUN ln -snf /build/build/work /app/build/work
WORKDIR /app

ENV DOCKER_DEV true
ENV NOKOGIRI_USE_SYSTEM_LIBRARIES 1

COPY tasks/install-system-build-dependencies /app/tasks/install-system-build-dependencies
COPY build/package_dependencies.sh /app/build/package_dependencies.sh
COPY tasks/helpers.sh /app/tasks/helpers.sh
RUN /app/tasks/install-system-build-dependencies

COPY Makefile.in /app/Makefile.in
COPY Taskfile.yml /app/Taskfile.yml
COPY configure /app/configure
COPY tasks/bootstrap-* /app/tasks/
RUN ./configure

COPY build/patches /app/build/patches
COPY tasks/deps /app/tasks/deps
RUN make deps

COPY tasks/build-deps /app/tasks/build-deps
RUN make build-deps

COPY src/api-umbrella/admin-ui/package.json /app/src/api-umbrella/admin-ui/package.json
COPY src/api-umbrella/admin-ui/yarn.lock /app/src/api-umbrella/admin-ui/yarn.lock
COPY src/api-umbrella/web-app/Gemfile /app/src/api-umbrella/web-app/Gemfile
COPY src/api-umbrella/web-app/Gemfile.lock /app/src/api-umbrella/web-app/Gemfile.lock
COPY tasks/app-deps /app/tasks/app-deps
RUN make app-deps

COPY . /app
RUN make
RUN make package

FROM ubuntu:16.04

COPY --from=build /build/build/package/work/build/core /tmp/package
RUN apt-get update && \
  apt-get -y install gdebi-core && \
  gdebi --non-interactive /tmp/package/*.deb && \
  apt-get -y --purge remove gdebi-core && \
  apt-get -y --purge autoremove && \
  rm -rf /tmp/package /var/lib/apt/lists/*

CMD ["api-umbrella", "run"]
