# Run build tasks, test tasks, and other generic tasks via the go-task tool:
# https://github.com/go-task/task
#
# The primary reason we're using this over something more standard like Make is
# that it provides a simple mechanism to skip tasks based on file checksums.
# This lets us more easily cache and skip steps in the CI and Docker
# development environment (since we only need to cache the build output and
# checksum files, rather than also needing to cache all the intermediate build
# files).
#
# A few general notes on the approach:
#
# - We mostly defer each task to a shell script to do the actual work.
# - For the build process, we use "stamp" files as outputs and also use those
#   within the dependency chain. We use these stamp files so that the
#   checksumming approach properly invalidates the entire chain of dependencies
#   when build files change (whereas just using "deps" in go-task doesn't fully
#   work for multiple levels of dependencies). So, for example, if the
#   libmaxminddb dependency changes, rebuilding it properly cascades and
#   triggers a rebuild of openresty (1st level dependency) and luarocks (2nd
#   level dependency).

version: "3"

output: interleaved

run: when_changed

tasks:
  deps:bundler:
    deps:
      - deps:rubygems
    cmds:
      - ./tasks/deps/bundler
    sources:
      - ./build/work/stamp/deps/rubygems
      - ./tasks/deps/bundler
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/bundler

  deps:elasticsearch:
    cmds:
      - ./tasks/deps/elasticsearch
    sources:
      - ./tasks/deps/elasticsearch
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/elasticsearch

  deps:icu4c:
    cmds:
      - ./tasks/deps/icu4c
    sources:
      - ./tasks/deps/icu4c
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/icu4c

  deps:libcidr:
    cmds:
      - ./tasks/deps/libcidr
    sources:
      - ./tasks/deps/libcidr
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libcidr

  deps:libestr:
    cmds:
      - ./tasks/deps/libestr
    sources:
      - ./tasks/deps/libestr
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libestr

  deps:libfastjson:
    cmds:
      - ./tasks/deps/libfastjson
    sources:
      - ./tasks/deps/libfastjson
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libfastjson

  deps:libmaxminddb:
    cmds:
      - ./tasks/deps/libmaxminddb
    sources:
      - ./tasks/deps/libmaxminddb
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/libmaxminddb

  deps:luarocks:
    deps:
      - deps:openresty
    cmds:
      - ./tasks/deps/luarocks
    sources:
      - ./build/work/stamp/deps/openresty
      - ./tasks/deps/luarocks
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/luarocks

  deps:mongodb:
    cmds:
      - ./tasks/deps/mongodb
    sources:
      - ./tasks/deps/mongodb
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/mongodb

  deps:mora:
    cmds:
      - ./tasks/deps/mora
    sources:
      - ./tasks/deps/mora
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/mora

  deps:openresty:
    deps:
      - deps:libmaxminddb
    cmds:
      - ./tasks/deps/openresty
    sources:
      - ./build/work/stamp/deps/libmaxminddb
      - ./tasks/deps/openresty
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/openresty

  deps:perp:
    cmds:
      - ./tasks/deps/perp
    sources:
      - ./tasks/deps/perp
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/perp

  deps:rsyslog:
    deps:
      - deps:libestr
      - deps:libfastjson
    cmds:
      - ./tasks/deps/rsyslog
    sources:
      - ./build/work/stamp/deps/libestr
      - ./build/work/stamp/deps/libfastjson
      - ./tasks/deps/rsyslog
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/rsyslog

  deps:ruby:
    cmds:
      - ./tasks/deps/ruby
    sources:
      - ./tasks/deps/ruby
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/ruby

  deps:rubygems:
    deps:
      - deps:ruby
    cmds:
      - ./tasks/deps/rubygems
    sources:
      - ./build/work/stamp/deps/ruby
      - ./tasks/deps/rubygems
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/rubygems

  deps:runit_svlogd:
    cmds:
      - ./tasks/deps/runit_svlogd
    sources:
      - ./tasks/deps/runit_svlogd
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/runit_svlogd

  deps:trafficserver:
    deps:
      - deps:openresty
    cmds:
      - ./tasks/deps/trafficserver
    sources:
      - ./build/work/stamp/deps/openresty
      - ./tasks/deps/trafficserver
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/deps/trafficserver

  deps:
    cmds:
      - task: deps:bundler
      - task: deps:elasticsearch
      - task: deps:icu4c
      - task: deps:libcidr
      - task: deps:luarocks
      - task: deps:mongodb
      - task: deps:mora
      - task: deps:openresty
      - task: deps:perp
      - task: deps:rsyslog
      - task: deps:runit_svlogd
      - task: deps:trafficserver

  build-deps:nodejs:
    cmds:
      - ./tasks/build-deps/nodejs
    sources:
      - ./tasks/build-deps/nodejs
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/build-deps/nodejs

  build-deps:yarn:
    deps:
      - build-deps:nodejs
    cmds:
      - ./tasks/build-deps/yarn
    sources:
      - ./build/work/stamp/build-deps/nodejs
      - ./tasks/build-deps/yarn
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/build-deps/yarn

  build-deps:
    cmds:
      - task: build-deps:yarn

  app-deps:admin-ui:yarn:
    deps:
      - build-deps:yarn
    cmds:
      - ./tasks/app-deps/admin-ui/yarn
    sources:
      - ./build/work/stamp/build-deps/yarn
      - ./src/api-umbrella/admin-ui/.yarnrc
      - ./src/api-umbrella/admin-ui/package.json
      - ./src/api-umbrella/admin-ui/yarn.lock
      - ./tasks/app-deps/admin-ui/yarn
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app-deps/admin-ui/yarn

  app-deps:lua:argparse:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/argparse
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/argparse
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/argparse

  app-deps:lua:cmsgpack:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/cmsgpack
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/cmsgpack
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/cmsgpack

  app-deps:lua:icu-date-ffi:
    deps:
      - deps:icu4c
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/icu-date-ffi
    sources:
      - ./build/work/stamp/deps/icu4c
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/icu-date-ffi
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/icu-date-ffi

  app-deps:lua:inspect:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/inspect
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/inspect
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/inspect

  app-deps:lua:libcidr-ffi:
    deps:
      - deps:libcidr
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/libcidr-ffi
    sources:
      - ./build/work/stamp/deps/libcidr
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/libcidr-ffi
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/libcidr-ffi

  app-deps:lua:luaposix:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/luaposix
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/luaposix
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/luaposix

  app-deps:lua:luasocket:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/luasocket
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/luasocket
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/luasocket

  app-deps:lua:lustache:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/lustache
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/lustache
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/lustache

  app-deps:lua:lyaml:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/lyaml
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/lyaml
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/lyaml

  app-deps:lua:penlight:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/penlight
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/penlight
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/penlight

  app-deps:lua:resty-auto-ssl:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-auto-ssl
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-auto-ssl
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-auto-ssl

  app-deps:lua:resty-http:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-http
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-http
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-http

  app-deps:lua:resty-logger-socket:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-logger-socket
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-logger-socket
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-logger-socket

  app-deps:lua:resty-shcache:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-shcache
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-shcache
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-shcache

  app-deps:lua:resty-txid:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-txid
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-txid
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-txid

  app-deps:lua:resty-uuid:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/resty-uuid
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/resty-uuid
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/resty-uuid

  app-deps:lua:shell-games:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/app-deps/lua/shell-games
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/app-deps/lua/shell-games
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/lua/shell-games

  app-deps:web-app:bundle:
    deps:
      - deps:bundler
    cmds:
      - ./tasks/app-deps/web-app/bundle
    sources:
      - ./build/work/stamp/deps/bundler
      - ./src/api-umbrella/web-app/Gemfile
      - ./src/api-umbrella/web-app/Gemfile.lock
      - ./tasks/app-deps/web-app/bundle
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/app-deps/web-app/bundle

  app-deps:
    cmds:
      - task: app-deps:admin-ui:yarn
      - task: app-deps:lua:argparse
      - task: app-deps:lua:cmsgpack
      - task: app-deps:lua:icu-date-ffi
      - task: app-deps:lua:inspect
      - task: app-deps:lua:libcidr-ffi
      - task: app-deps:lua:luaposix
      - task: app-deps:lua:luasocket
      - task: app-deps:lua:lustache
      - task: app-deps:lua:lyaml
      - task: app-deps:lua:penlight
      - task: app-deps:lua:resty-auto-ssl
      - task: app-deps:lua:resty-http
      - task: app-deps:lua:resty-logger-socket
      - task: app-deps:lua:resty-shcache
      - task: app-deps:lua:resty-txid
      - task: app-deps:lua:resty-uuid
      - task: app-deps:lua:shell-games
      - task: app-deps:web-app:bundle

  app:admin-ui:build:
    deps:
      - app-deps:admin-ui:yarn
    cmds:
      - ./tasks/app/admin-ui/build
    sources:
      - ./build/work/stamp/app-deps/admin-ui/yarn
      - ./src/api-umbrella/admin-ui/app/**/*.hbs
      - ./src/api-umbrella/admin-ui/app/**/*.html
      - ./src/api-umbrella/admin-ui/app/**/*.js
      - ./src/api-umbrella/admin-ui/app/**/*.scss
      - ./src/api-umbrella/admin-ui/config/**/*.js
      - ./src/api-umbrella/admin-ui/ember-cli-build.js
      - ./src/api-umbrella/admin-ui/lib/**/*.js
      - ./tasks/app/admin-ui/build
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/admin-ui/build

  app:core:
    deps:
      - app:admin-ui:build
      - app:web-app:precompile
    cmds:
      - ./tasks/app/core
    sources:
      - ./build/work/stamp/app/admin-ui/build
      - ./build/work/stamp/app/web-app/precompile
      - ./tasks/app/core
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/core

  app:static-site:
    deps:
      - build-deps:nodejs
      - deps:bundler
    cmds:
      - ./tasks/app/static-site
    sources:
      - ./build/work/stamp/build-deps/nodejs
      - ./build/work/stamp/deps/bundler
      - ./tasks/app/static-site
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/static-site

  app:web-app:precompile:
    deps:
      - build-deps:nodejs
      - app-deps:web-app:bundle
    cmds:
      - ./tasks/app/web-app/precompile
    sources:
      - ./build/work/stamp/app-deps/web-app/bundle
      - ./build/work/stamp/build-deps/nodejs
      - ./src/api-umbrella/web-app/app/assets/**/*.css
      - ./src/api-umbrella/web-app/app/assets/**/*.erb
      - ./src/api-umbrella/web-app/app/assets/**/*.js
      - ./src/api-umbrella/web-app/app/assets/**/*.scss
      - ./tasks/app/web-app/precompile
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/app/web-app/precompile

  app:
    cmds:
      - task: app:core
      - task: app:static-site

  all:
    cmds:
      - task: build-deps
      - task: deps
      - task: app-deps
      - task: app

  test-deps:bundle:
    deps:
      - deps:bundler
    cmds:
      - ./tasks/test-deps/bundle
    sources:
      - ./build/work/stamp/deps/bundler
      - ./Gemfile
      - ./Gemfile.lock
      - ./tasks/test-deps/bundle
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/bundle

  test-deps:elasticsearch6:
    cmds:
      - ./tasks/test-deps/elasticsearch6
    sources:
      - ./tasks/test-deps/elasticsearch6
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/elasticsearch6

  test-deps:elasticsearch7:
    cmds:
      - ./tasks/test-deps/elasticsearch7
    sources:
      - ./tasks/test-deps/elasticsearch7
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/elasticsearch7

  test-deps:glauth:
    cmds:
      - ./tasks/test-deps/glauth
    sources:
      - ./tasks/test-deps/glauth
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/glauth

  test-deps:lua:luacheck:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/test-deps/lua/luacheck
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/test-deps/lua/luacheck
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/test-deps/lua/luacheck

  test-deps:lua:penlight:
    deps:
      - deps:luarocks
    cmds:
      - ./tasks/test-deps/lua/penlight
    sources:
      - ./build/work/stamp/deps/luarocks
      - ./tasks/test-deps/lua/penlight
      - ./tasks/helpers.sh
      - ./tasks/helpers/lua.sh
    generates:
      - ./build/work/stamp/test-deps/lua/penlight

  test-deps:mailhog:
    cmds:
      - ./tasks/test-deps/mailhog
    sources:
      - ./tasks/test-deps/mailhog
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/mailhog

  test-deps:mongo-orchestration:
    cmds:
      - ./tasks/test-deps/mongo-orchestration
    sources:
      - ./tasks/test-deps/mongo-orchestration
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/mongo-orchestration

  test-deps:shellcheck:
    cmds:
      - ./tasks/test-deps/shellcheck
    sources:
      - ./tasks/test-deps/shellcheck
      - ./tasks/helpers.sh
    generates:
      - ./build/work/stamp/test-deps/shellcheck

  test-deps:
    cmds:
      - task: test-deps:bundle
      - task: test-deps:elasticsearch6
      - task: test-deps:elasticsearch7
      - task: test-deps:glauth
      - task: test-deps:lua:luacheck
      - task: test-deps:lua:penlight
      - task: test-deps:mailhog
      - task: test-deps:mongo-orchestration
      - task: test-deps:shellcheck

  lint:js:
    deps:
      - app-deps:admin-ui:yarn
    cmds:
      - ./tasks/lint/js

  lint:lua:
    deps:
      - test-deps:lua:luacheck
    cmds:
      - ./tasks/lint/lua

  lint:resty:
    deps:
      - test-deps:lua:penlight
    cmds:
      - ./tasks/lint/resty/run

  lint:ruby:
    deps:
      - test-deps:bundle
    cmds:
      - ./tasks/lint/ruby

  lint:shell:
    deps:
      - test-deps:shellcheck
    cmds:
      - ./tasks/lint/shell

  lint:
    cmds:
      - task: lint:js
      - task: lint:lua
      - task: lint:resty
      - task: lint:ruby
      - task: lint:shell

  outdated:
    cmds:
      - ./tasks/outdated

  test:
    deps:
      - all
      - test-deps
    cmds:
      - ./tasks/test/default

  clean:dev:
    cmds:
      - ./tasks/clean/dev

  distclean:
    cmds:
      - ./tasks/distclean

  install:
    cmds:
      - ./tasks/install

  package:
    cmds:
      - ./tasks/package

  install-system-build-dependencies:
    cmds:
      - ./tasks/install-system-build-dependencies

  default:
    cmds:
      - task: all
