#!/usr/bin/env bash

lua_shell_games_test_version="1.1.0"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

test_opm_install "GUI/lua-shell-games" "$lua_shell_games_test_version"

stamp
