#!/usr/bin/env bash

elasticsearch7_version="7.0.1"
elasticsearch7_hash="26d8a80f6d5066acf5fef32fc9b51e85b77440eb"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$elasticsearch7_version-linux-x86_64.tar.gz" "sha1" "$elasticsearch7_hash"
extract_download "elasticsearch-$elasticsearch7_version-linux-x86_64.tar.gz"

mkdir -p "$TEST_INSTALL_PREFIX/elasticsearch7"
rsync -a -v --checksum --delete-after "elasticsearch-$elasticsearch7_version/" "$TEST_INSTALL_PREFIX/elasticsearch7/"
"$TEST_INSTALL_PREFIX/elasticsearch7/bin/elasticsearch-keystore" create
chmod 660 "$TEST_INSTALL_PREFIX/elasticsearch7/config/elasticsearch.keystore"

stamp
