#!/usr/bin/env bash

elasticsearch5_version="5.6.15"
elasticsearch5_hash="42d2519fd7d47e5b0bbef05d402ff0f66fbbe2ca"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$elasticsearch5_version.tar.gz" "sha1" "$elasticsearch5_hash"
extract_download "elasticsearch-$elasticsearch5_version.tar.gz"

mkdir -p "$TEST_INSTALL_PREFIX"
rsync -a -v --checksum --delete-after "elasticsearch-$elasticsearch5_version/" "$TEST_INSTALL_PREFIX/elasticsearch5/"
"$TEST_INSTALL_PREFIX/elasticsearch5/bin/elasticsearch-keystore" create
chmod 660 "$TEST_INSTALL_PREFIX/elasticsearch5/config/elasticsearch.keystore"

stamp
