#!/usr/bin/env bash

elasticsearch6_version="6.3.0"
elasticsearch6_hash="e9f6b4a23024c1849cb441db44f4495bba7669b5"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$elasticsearch6_version.tar.gz" "sha1" "$elasticsearch6_hash"
extract_download "elasticsearch-$elasticsearch6_version.tar.gz"

mkdir -p "$TEST_INSTALL_PREFIX"
rsync -a -v --checksum --delete-after "elasticsearch-$elasticsearch6_version/" "$TEST_INSTALL_PREFIX/elasticsearch6/"
"$TEST_INSTALL_PREFIX/elasticsearch6/bin/elasticsearch-keystore" create
chmod 660 "$TEST_INSTALL_PREFIX/elasticsearch6/config/elasticsearch.keystore"

stamp
