#!/usr/bin/env bash

elasticsearch6_version="6.8.10"
elasticsearch6_hash="01410753ae065fc088f731217ee823e17f3de267"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$elasticsearch6_version.tar.gz" "sha1" "$elasticsearch6_hash"
extract_download "elasticsearch-$elasticsearch6_version.tar.gz"

mkdir -p "$TEST_INSTALL_PREFIX/elasticsearch6"
rsync -a -v --checksum --delete-after "elasticsearch-$elasticsearch6_version/" "$TEST_INSTALL_PREFIX/elasticsearch6/"
"$TEST_INSTALL_PREFIX/elasticsearch6/bin/elasticsearch-keystore" create
chmod 660 "$TEST_INSTALL_PREFIX/elasticsearch6/config/elasticsearch.keystore"

stamp
