#!/usr/bin/env bash

elasticsearch5_version="5.6.14"
elasticsearch5_hash="392e98ebd549aba91f3041c59fe0d7be1abbd229"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$elasticsearch5_version.tar.gz" "sha1" "$elasticsearch5_hash"
extract_download "elasticsearch-$elasticsearch5_version.tar.gz"

mkdir -p "$TEST_INSTALL_PREFIX"
rsync -a -v --checksum --delete-after "elasticsearch-$elasticsearch5_version/" "$TEST_INSTALL_PREFIX/elasticsearch5/"
"$TEST_INSTALL_PREFIX/elasticsearch5/bin/elasticsearch-keystore" create
chmod 660 "$TEST_INSTALL_PREFIX/elasticsearch5/config/elasticsearch.keystore"

stamp
