#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

glauth_version="2.2.1"
glauth_hash="9f85938b248aba01a3d100de7bd4cdcf3c7b40688973a89efe45001eaf262028"
if [ "$TARGETARCH" == "arm64" ]; then
  glauth_hash="dcffeb30b976fd74412a6c05ea663121694e2fc54e6c85fa2e2910c014a03406"
fi

task_working_dir
download "https://github.com/glauth/glauth/releases/download/v$glauth_version/glauth-linux-${TARGETARCH}" "sha256" "$glauth_hash"

install -D -m 755 "_persist/downloads/glauth-linux-${TARGETARCH}" "$TEST_INSTALL_PREFIX/bin/glauth"

stamp
