#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

glauth_version="2.2.0"
glauth_hash="546aa37ee96def22e24a93f77747bd16dccaa39dd09394e534beef89a5a7233c"
if [ "$TARGETARCH" == "arm64" ]; then
  glauth_hash="6ea654b58f9dbdc63f67e0f0c4cc033797c09f488c2dd349a4d3e9a0754db137"
fi

task_working_dir
download "https://github.com/glauth/glauth/releases/download/v$glauth_version/linux${TARGETARCH}.zip" "sha256" "$glauth_hash"
rm -rf "_persist/downloads/linux${TARGETARCH}"
unzip "_persist/downloads/linux${TARGETARCH}.zip" -d "_persist/downloads/linux${TARGETARCH}"

install -D -m 755 "_persist/downloads/linux${TARGETARCH}/glauth" "$TEST_INSTALL_PREFIX/bin/glauth"

stamp
