#!/usr/bin/env bash

mailhog_version="1.0.1"
mailhog_hash="b5628956d35c9d2df3df30f980365df4"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://github.com/mailhog/MailHog/releases/download/v$mailhog_version/MailHog_linux_amd64" "md5" "$mailhog_hash"

install -D -m 755 _persist/downloads/MailHog_linux_amd64 "$TEST_INSTALL_PREFIX/bin/mailhog"

stamp
