#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

mailpit_version="1.14.1"
mailpit_hash="e9062eec62bf5ede6a23b1a41da2cf641434a2302ae873498020bc73a6d18ddd"
if [ "$TARGETARCH" == "arm64" ]; then
  mailpit_hash="44cd6c5578c90804441658221e3ed478faf5892dc97d57a0dcf5ccf25cc8226a"
fi

task_working_dir
download "https://github.com/axllent/mailpit/releases/download/v${mailpit_version}/mailpit-linux-${TARGETARCH}.tar.gz" "sha256" "$mailpit_hash"
extract_download "mailpit-linux-${TARGETARCH}.tar.gz"

install -D -m 755 "mailpit" "$TEST_INSTALL_PREFIX/bin/mailpit"

stamp
