#!/usr/bin/env bash

mongo_orchestration_version="0.7.0"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir

rm -rf "$TEST_INSTALL_PREFIX/mongo-orchestration"
virtualenv "$TEST_INSTALL_PREFIX/mongo-orchestration"
"$TEST_INSTALL_PREFIX/mongo-orchestration/bin/pip" install --ignore-installed "mongo-orchestration==$mongo_orchestration_version"
ln -snf "$TEST_INSTALL_PREFIX/mongo-orchestration/bin/mongo-orchestration" "$TEST_INSTALL_PREFIX/bin/mongo-orchestration"

stamp
