#!/usr/bin/env bash

openldap_version="2.4.50"
openldap_hash="82f576e0d0d334e9e798d9de8936683546247bb9"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://www.openldap.org/software/download/OpenLDAP/openldap-release/openldap-$openldap_version.tgz" "sha1" "$openldap_hash"
extract_download "openldap-$openldap_version.tgz"

cd "openldap-$openldap_version"
./configure --prefix="$TEST_INSTALL_PREFIX" --disable-backends --enable-mdb
make -j"$NPROC"
make depend
make install

stamp
