#!/usr/bin/env bash

phantomjs_version="2.1.1"
phantomjs_hash="1c947d57fce2f21ce0b43fe2ed7cd361"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-$phantomjs_version-linux-x86_64.tar.bz2" "md5" "$phantomjs_hash"
extract_download "phantomjs-$phantomjs_version-linux-x86_64.tar.bz2"

install -D -m 755 "phantomjs-$phantomjs_version-linux-x86_64/bin/phantomjs" "$TEST_INSTALL_PREFIX/bin/phantomjs"

stamp
