#!/usr/bin/env bash


set -e -u -x
source ./tasks/helpers.sh

shellcheck_version="0.11.0"
shellcheck_hash="8c3be12b05d5c177a04c29e3c78ce89ac86f1595681cab149b65b97c4e227198"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="x86_64"
elif [ "$TARGETARCH" == "arm64" ]; then
  download_arch="aarch64"
  shellcheck_hash="12b331c1d2db6b9eb13cfca64306b1b157a86eb69db83023e261eaa7e7c14588"
fi

task_working_dir
download "https://github.com/koalaman/shellcheck/releases/download/v$shellcheck_version/shellcheck-v$shellcheck_version.linux.${download_arch}.tar.xz" "sha256" "$shellcheck_hash"
extract_download "shellcheck-v$shellcheck_version.linux.${download_arch}.tar.xz"

install -D -m 755 "shellcheck-v$shellcheck_version/shellcheck" "$TEST_INSTALL_PREFIX/bin/shellcheck"

stamp
