#!/usr/bin/env bash

shellcheck_version="0.7.0"
shellcheck_hash="84e06bee3c8b8c25f46906350fb32708f4b661636c04e55bd19cdd1071265112d84906055372149678d37f09a1667019488c62a0561b81fe6a6b45ad4fae4ac0"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://storage.googleapis.com/shellcheck/shellcheck-v$shellcheck_version.linux.x86_64.tar.xz" "sha512" "$shellcheck_hash"
extract_download "shellcheck-v$shellcheck_version.linux.x86_64.tar.xz"

install -D -m 755 "shellcheck-v$shellcheck_version/shellcheck" "$TEST_INSTALL_PREFIX/bin/shellcheck"

stamp
