#!/usr/bin/env bash

shellcheck_version="0.8.0"
shellcheck_hash="89317d97adb341e627b709e86477734ce236e9fb290de8a8c41cdc62769a3225622fa609deffebeabe9edb71f5639a086f61b677947e3ec4bc07c540fcbd0973"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://github.com/koalaman/shellcheck/releases/download/v$shellcheck_version/shellcheck-v$shellcheck_version.linux.x86_64.tar.xz" "sha512" "$shellcheck_hash"
extract_download "shellcheck-v$shellcheck_version.linux.x86_64.tar.xz"

install -D -m 755 "shellcheck-v$shellcheck_version/shellcheck" "$TEST_INSTALL_PREFIX/bin/shellcheck"

stamp
