#!/usr/bin/env bash

unbound_version="1.9.3"
unbound_hash="1b55dd9170e4bfb327fb644de7bbf7f0541701149dff3adf1b63ffa785f16dfa"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://www.unbound.net/downloads/unbound-$unbound_version.tar.gz" "sha256" "$unbound_hash"
extract_download "unbound-$unbound_version.tar.gz"

cd "unbound-$unbound_version"
./configure --prefix="$TEST_INSTALL_PREFIX"
make -j"$NPROC"
make install

stamp
