#!/usr/bin/env bash

unbound_version="1.9.2"
unbound_hash="6f7acec5cf451277fcda31729886ae7dd62537c4f506855603e3aa153fcb6b95"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://www.unbound.net/downloads/unbound-$unbound_version.tar.gz" "sha256" "$unbound_hash"
extract_download "unbound-$unbound_version.tar.gz"

cd "unbound-$unbound_version"
./configure --prefix="$TEST_INSTALL_PREFIX"
make -j"$NPROC"
make install

stamp
