#!/usr/bin/env bash

unbound_version="1.10.1"
unbound_hash="b73677c21a71cf92f15cc8cfe76a3d875e40f65b6150081c39620b286582d536"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://www.unbound.net/downloads/unbound-$unbound_version.tar.gz" "sha256" "$unbound_hash"
extract_download "unbound-$unbound_version.tar.gz"

cd "unbound-$unbound_version"
./configure --prefix="$TEST_INSTALL_PREFIX"
make -j"$NPROC"
make install

stamp
