baseURL: /
languageCode: en-us
title: My New Hugo Site
params:
  githubRepoUrl: https://github.com/NREL/api-umbrella
  apiUmbrellaApiKey: DEMO_KEY
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
