#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

set -x
(
  cd "$SOURCE_DIR/src/api-umbrella/admin-ui"
  PATH="$DEV_PATH" yarn run lint:js
  PATH="$DEV_PATH" yarn run lint:hbs
)

(
  cd "$SOURCE_DIR/src/api-umbrella/web-app"
  PATH="$DEV_PATH" ./node_modules/.bin/eslint .
)
