#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

cd "$SOURCE_DIR/src"

rm -rf "$APP_VENDOR_LUA_DIR"

extra_args=(
  "--only-deps"
  "--pin"
)

luarocks_install "./api-umbrella-git-1.rockspec" "git-1" "${extra_args[@]}"
