#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/lua.sh

cd "$SOURCE_DIR/src"

extra_args=(
  "--only-deps"
  "--pin"
  "CIDR_DIR=$STAGE_EMBEDDED_DIR"
)

luarocks_install "./api-umbrella-git-1.rockspec" "git-1" "${extra_args[@]}"
