source "https://rubygems.org"

gem "rake", "~> 11.2.2"

# Tests
gem "minitest", "~> 5.9.0"

# More test outputs
gem "minitest-reporters", "~> 1.1.10"

# Running background processes
gem "childprocess", "~> 0.5.9"

# Making HTTP requests
gem "typhoeus", "~> 1.0.2"

# JSON parsing
gem "multi_json", "~> 1.12.1"
gem "oj", "~> 2.17.1"

# Database libraries
gem "mongo", "~> 2.2.5"

# Useful additions
gem "activesupport", "~> 5.0.0"

gem "awesome_print", "~> 1.7.0"
