#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

shopt -s globstar

ln -snf "$WORK_DIR/tasks/app-deps/admin-ui/yarn/_persist/node_modules" "$SOURCE_DIR/src/api-umbrella/admin-ui/node_modules"
ln -snf "$WORK_DIR/tasks/app-deps/web-app/yarn/_persist/node_modules" "$SOURCE_DIR/src/api-umbrella/web-app/node_modules"

# Due to some of our hard-coded assumptions about running things on specific
# nodes, ensure that the CI is at least running on the number of nodes
# expected.
if [[ "$CIRCLE_NODE_TOTAL" -lt 3 ]]; then
  echo "Expected CIRCLE_NODE_TOTAL to be greater than or equal to 3"
  exit 1
fi

# Always run the lint tests on the first node (since these are quick and only
# need to be run on a single node).
if [ "$CIRCLE_NODE_INDEX" -eq "0" ]; then
  time make lint
fi

# Circle's parallel command will pass this script a list of test files to run
# on this node as arguments. Pass those along to the rake task via the TESTS
# environment variable.
tests="$(circleci tests glob test/**/test_*.rb | circleci tests split --split-by=timings)"
env TESTOPTS="--ci-dir=./test/tmp/reports" TESTS="${tests[*]}" N=12 make test
