#!/usr/bin/env bash

bundler_version="2.0.2"

set -e -u -x
source ./tasks/helpers.sh

PATH="$DEV_PATH" gem uninstall bundler --all --executables --force || true
PATH="$DEV_PATH" gem install bundler --version $bundler_version --no-document --env-shebang --force

stamp
