#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

crane_version="0.16.1"
crane_hash="115dc84d14c5adc89c16e3fa297e94f06a9ec492bb1dc730da624850b77c9be2"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="x86_64"
elif [ "$TARGETARCH" == "arm64" ]; then
  crane_hash="9e226779377a20713f16ac94dec9f6c17f698834ea40c33a6c86f9de8845722b"
fi

task_working_dir
download "https://github.com/google/go-containerregistry/releases/download/v${crane_version}/go-containerregistry_Linux_${download_arch}.tar.gz" "sha256" "$crane_hash"
extract_download "go-containerregistry_Linux_${download_arch}.tar.gz"

install -D -m 755 "crane" "$DEV_INSTALL_PREFIX/bin/crane"

stamp
