#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

crane_version="0.13.0"
crane_hash="b06641f6cd08c509d5f1b234076269bfbb512f91e7ba4f796adb8c4b1626c9b7"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="x86_64"
elif [ "$TARGETARCH" == "arm64" ]; then
  crane_hash="b26d322276cf6934a162200a1bde19d9318e4b9656a357527a7465c3bf53f4c2"
fi

task_working_dir
download "https://github.com/google/go-containerregistry/releases/download/v${crane_version}/go-containerregistry_Linux_${download_arch}.tar.gz" "sha256" "$crane_hash"
extract_download "go-containerregistry_Linux_${download_arch}.tar.gz"

install -D -m 755 "crane" "$DEV_INSTALL_PREFIX/bin/crane"

stamp
