#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

crane_version="0.15.1"
crane_hash="d4710014a3bd135eb1d4a9142f509cfd61d2be242e5f5785788e404448a4f3f2"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="x86_64"
elif [ "$TARGETARCH" == "arm64" ]; then
  crane_hash="ce099216f4aedb2d9ec1f44a05befddf4526b76e327b8bfe137f4c860cddc969"
fi

task_working_dir
download "https://github.com/google/go-containerregistry/releases/download/v${crane_version}/go-containerregistry_Linux_${download_arch}.tar.gz" "sha256" "$crane_hash"
extract_download "go-containerregistry_Linux_${download_arch}.tar.gz"

install -D -m 755 "crane" "$DEV_INSTALL_PREFIX/bin/crane"

stamp
