#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

hugo_version="0.136.5"
hugo_hash="b7be7c1abb0b077ce079f634c479791dfadaaf3236fa47948b0290a6b0bf70ff"
if [ "$TARGETARCH" == "arm64" ]; then
  hugo_hash="8ebc7f58b7a188b608aa851788d1e490a9ebe4857dfb9238ab70ea93be08d9c4"
fi

task_working_dir
download "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz" "sha256" "$hugo_hash"
extract_download "hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz"

install -D -m 755 "hugo" "$DEV_INSTALL_PREFIX/bin/hugo"

stamp
