#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

hugo_version="0.110.0"
hugo_hash="008519ae58e7650097da8d557d788841f057359b3b695508abcfa855e9779b38"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="64bit"
elif [ "$TARGETARCH" == "arm64" ]; then
  download_arch="arm64"
  hugo_hash="fa49e9631c6dc7be6398103be19eff56c62359061863e53952d1e4b5f307f298"
fi

task_working_dir
download "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_Linux-${download_arch}.tar.gz" "sha256" "$hugo_hash"
extract_download "hugo_extended_${hugo_version}_Linux-${download_arch}.tar.gz"

install -D -m 755 "hugo" "$DEV_INSTALL_PREFIX/bin/hugo"

stamp
