#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

hugo_version="0.147.6"
hugo_hash="7381ce7bb2129a5e3ea74fa924d9ac89d1df01dd30d6df3c00ad77b83788efa1"
if [ "$TARGETARCH" == "arm64" ]; then
  hugo_hash="6ecf715e67b21427541b3678a7529dd9e457ef27611c846f1c8116b7e8c7f6b3"
fi

task_working_dir
download "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz" "sha256" "$hugo_hash"
extract_download "hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz"

install -D -m 755 "hugo" "$DEV_INSTALL_PREFIX/bin/hugo"

stamp
