#!/usr/bin/env bash

nodejs_version="14.17.5"
nodejs_hash="2d759de07a50cd7f75bd73d67e97b0d0e095ee3c413efac7d1b3d1e84ed76fff"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://nodejs.org/dist/v$nodejs_version/node-v$nodejs_version-linux-x64.tar.xz" "sha256" "$nodejs_hash"
extract_download "node-v$nodejs_version-linux-x64.tar.xz"

mkdir -p "$DEV_INSTALL_PREFIX"
rsync -a -v "node-v$nodejs_version-linux-x64/" "$DEV_INSTALL_PREFIX/"

stamp
