#!/usr/bin/env bash


set -e -u -x
source ./tasks/helpers.sh

nodejs_version="22.13.1"
nodejs_hash="0d2a5af33c7deab5555c8309cd3f373446fe1526c1b95833935ab3f019733b3b"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="x64"
elif [ "$TARGETARCH" == "arm64" ]; then
  nodejs_hash="0a237c413ccbab920640438bf6e1a32edb19845bdc21f0e1cd5b91545ce1c126"
fi

task_working_dir
download "https://nodejs.org/dist/v$nodejs_version/node-v$nodejs_version-linux-${download_arch}.tar.xz" "sha256" "$nodejs_hash"
extract_download "node-v$nodejs_version-linux-${download_arch}.tar.xz"

mkdir -p "$DEV_INSTALL_PREFIX"
rsync -a --itemize-changes "node-v$nodejs_version-linux-${download_arch}/" "$DEV_INSTALL_PREFIX/"

stamp
