#!/usr/bin/env bash

nodejs_version="8.11.3"
nodejs_hash="08e2fcfea66746bd966ea3a89f26851f1238d96f86c33eaf6274f67fce58421a"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://nodejs.org/dist/v$nodejs_version/node-v$nodejs_version-linux-x64.tar.xz" "sha256" "$nodejs_hash"
extract_download "node-v$nodejs_version-linux-x64.tar.xz"

rsync -a -v "node-v$nodejs_version-linux-x64/" "$DEV_INSTALL_PREFIX/"

stamp
