#!/usr/bin/env bash

ruby_version="2.6.6"
ruby_hash="f08b779079ecd1498e6a2548c39a86144c6c784dcec6f7e8a93208682eb8306e"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-$ruby_version.tar.bz2" "sha256" "$ruby_hash"
extract_download "ruby-$ruby_version.tar.bz2"

cd "ruby-$ruby_version"
./configure \
  --prefix="$DEV_INSTALL_PREFIX" \
  --enable-load-relative \
  --disable-rpath \
  --disable-install-doc
make -j"$NPROC"
make install

stamp
