#!/usr/bin/env bash

ruby_version="2.6.4"
ruby_hash="fa1ecc67b99fa13201499002669412eae7cfbe2c30c4f1f4526e8491edfc5fa7"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://cache.ruby-lang.org/pub/ruby/2.6/ruby-$ruby_version.tar.bz2" "sha256" "$ruby_hash"
extract_download "ruby-$ruby_version.tar.bz2"

cd "ruby-$ruby_version"
./configure \
  --prefix="$DEV_INSTALL_PREFIX" \
  --enable-load-relative \
  --disable-rpath \
  --disable-install-doc
make -j"$NPROC"
make install

stamp
