#!/usr/bin/env bash

yarn_version="1.22.18"
yarn_hash="fd220e06ecd3a3cc86a38f9215efdd67"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://github.com/yarnpkg/yarn/releases/download/v$yarn_version/yarn-v$yarn_version.tar.gz" "md5" "$yarn_hash"
extract_download "yarn-v$yarn_version.tar.gz"

mkdir -p "$DEV_INSTALL_PREFIX/yarn"
rsync -a --itemize-changes --delete "yarn-v$yarn_version/" "$DEV_INSTALL_PREFIX/yarn/"

mkdir -p "$DEV_INSTALL_PREFIX/bin"
(cd "$DEV_INSTALL_PREFIX/bin" && ln -snf ../yarn/bin/yarn ./yarn)

# Remove the previous bin symlink that was necessary.
rm -f "$DEV_INSTALL_PREFIX/bin/yarn.js"

stamp
