#!/usr/bin/env bash

yarn_version="1.7.0"
yarn_hash="e149b4cc0c2cb903551a0b857a2b3c78"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://github.com/yarnpkg/yarn/releases/download/v$yarn_version/yarn-v$yarn_version.tar.gz" "md5" "$yarn_hash"
extract_download "yarn-v$yarn_version.tar.gz"

rsync -a -v --delete "yarn-v$yarn_version/" "$DEV_INSTALL_PREFIX/yarn/"
cd "$DEV_INSTALL_PREFIX/bin" && ln -snf ../yarn/bin/yarn ./yarn

# Remove the previous bin symlink that was necessary.
rm -f "$DEV_INSTALL_PREFIX/bin/yarn.js"

stamp
