FROM ubuntu:bionic

# Copy binary file
# It requires deb package to have been built using: make -C build/package -j4 docker_ubuntu1604 
COPY api-umbrella_0.15.0-0.1.pre2~bionic_amd64.deb .

# Install API Umbrella
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y curl ./api-umbrella_0.15.0-0.1.pre2~bionic_amd64.deb && \
    rm -rf /var/lib/apt/lists/*

# Define mountable directories
VOLUME ["/etc/api-umbrella", "/opt/api-umbrella/var/db", "/opt/api-umbrella/var/log"]

# Expose HTTP and HTTPS ports
EXPOSE 80 443

# Run the API Umbrella service
CMD ["api-umbrella", "run"]
