#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

task_working_dir

# Install into the task's special _persist directory so that these dependencies
# for the tasks/app/core task are still present if core needs to be re-run, but
# not this task.
mkdir -p _persist
cd _persist

node_modules_dir="$WORK_DIR/tasks/app-deps/admin-ui/yarn/_persist/node_modules"
mkdir -p json

for locale_path in "$SOURCE_DIR"/locale/*.po; do
  locale="${locale_path##*/}"
  locale="${locale%%.*}"
  # Use `--no-deprecation` to fix issues in NodeJS 16 until new version of
  # po2json is released: https://github.com/mikeedwards/po2json/issues/103
  PATH="$DEV_INSTALL_PREFIX/bin:$DEFAULT_PATH" node --no-deprecation "$node_modules_dir/.bin/po2json" \
    --format=jed1.x \
    --domain=api-umbrella \
    "$locale_path" \
    "./json/$locale.json"
done

stamp
