#!/usr/bin/env bash

api_umbrella_static_site_version="8c961e594a14d94de7fe34ed401ec5979f5395d7"
api_umbrella_static_site_hash="a9897573a886614ddf8501e54bbc3424"

set -e -u -x
source ./tasks/helpers.sh
source ./tasks/helpers/detect_os_release.sh

task_working_dir
download "https://github.com/NREL/api-umbrella-static-site/archive/$api_umbrella_static_site_version.tar.gz" "md5" "$api_umbrella_static_site_hash"
extract_download "$api_umbrella_static_site_version.tar.gz"

detect_os_release
if [[ "$ID_NORMALIZED" == "rhel" && "$VERSION_ID" == "6" ]]; then
  # GCC 4.6+ for compiling libsass/sassc
  export CC=/opt/rh/devtoolset-7/root/usr/bin/gcc
  export CXX=/opt/rh/devtoolset-7/root/usr/bin/g++
fi

cd "api-umbrella-static-site-$api_umbrella_static_site_version"
export PATH="$DEV_PATH"
perl -0 -p -i -e 's/BUNDLED WITH[\n\r]+.+$//igs' Gemfile.lock
bundle config --local build.nokogiri --use-system-libraries
bundle config --local path "$(pwd)/vendor/bundle"
bundle install
bundle exec middleman build
rm -rf "$STAGE_EMBEDDED_DIR/apps/static-site/releases"
mkdir -p "$STAGE_EMBEDDED_DIR/apps/static-site/releases/0/build"
rsync -a ./build/ "$STAGE_EMBEDDED_DIR/apps/static-site/releases/0/build/"
(cd "$STAGE_EMBEDDED_DIR/apps/static-site" && ln -snf releases/0 ./current)

stamp
