#!/usr/bin/env bash

api_umbrella_static_site_version="c34e7ee72e1b3e895861f14a5ead0f55ae30661c"
api_umbrella_static_site_hash="3adbca358604fbaad51e8947407d8569"

set -e -u -x
source ./tasks/helpers.sh

task_working_dir
download "https://github.com/NREL/api-umbrella-static-site/archive/$api_umbrella_static_site_version.tar.gz" "md5" "$api_umbrella_static_site_hash"
extract_download "$api_umbrella_static_site_version.tar.gz"

cd "api-umbrella-static-site-$api_umbrella_static_site_version"
PATH="$DEV_PATH" bundle update --bundler
PATH="$DEV_PATH" bundle config --local build.nokogiri --use-system-libraries
PATH="$DEV_PATH" bundle config --local path "$(pwd)/vendor/bundle"
PATH="$DEV_PATH" bundle install
PATH="$DEV_PATH" bundle exec middleman build
rm -rf "$STAGE_EMBEDDED_DIR/apps/static-site/releases"
mkdir -p "$STAGE_EMBEDDED_DIR/apps/static-site/releases/0/build"
rsync -a ./build/ "$STAGE_EMBEDDED_DIR/apps/static-site/releases/0/build/"
(cd "$STAGE_EMBEDDED_DIR/apps/static-site" && ln -snf releases/0 ./current)

stamp
