#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

task_working_dir

# Install into the task's special _persist directory so that these dependencies
# for the tasks/app/core task are still present if core needs to be re-run, but
# not this task.
mkdir -p _persist
cd _persist

export PATH="$STAGE_EMBEDDED_PATH"
export BUNDLE_GEMFILE="$SOURCE_DIR/src/api-umbrella/web-app/Gemfile"
export BUNDLE_APP_CONFIG="$WORK_DIR/tasks/app-deps/web-app/bundle/_persist/.bundle"
RAILS_TMP_PATH="$(pwd)/tmp"
export RAILS_TMP_PATH
RAILS_PUBLIC_PATH="$(pwd)/public"
export RAILS_PUBLIC_PATH
export RAILS_ENV=production
export RAILS_SECRET_TOKEN=temp
export RAILS_ASSETS_PRECOMPILE=true
bundle exec rake -f "$SOURCE_DIR/src/api-umbrella/web-app/Rakefile" assets:clobber assets:precompile

stamp
