source "https://rubygems.org"

ruby "~> 2.4.10"

gem "rails", "~> 4.2.11", ">= 4.2.11.1"

# Rails app server
gem "puma", "~> 5.0"

# Error notification service (optional)
gem "rollbar", "~> 3.0"

# Abort requests that take too long
gem "rack-timeout", "~> 0.6.0", :require => "rack/timeout/base"

# For proxying HTTP requests to password-protected places for admins.
gem "rack-proxy", "~> 0.6.4"

# JSON handling
gem "multi_json", "~> 1.15.0"
gem "oj", "~> 3.10", :platforms => [:ruby]

# MongoDB
gem "mongoid", "~> 5.4"

# Soft-delete
gem "mongoid-paranoia", "~> 2.0.0"

# Versioning for mongoid
gem "mongoid_delorean", "~> 1.3.0"

# Display deeply nested validation errors on embedded documents.
gem "mongoid-embedded-errors", "~> 2.1.1"

# Data migrations
gem "mongoid_rails_migrations", "~> 1.2.1"

# Rails cache store using mongo.
#
# Use master from git for Rails 4 compatibility.
gem "mongoid_store", :git => "https://github.com/GUI/mongoid_store.git"

# Elasticsearch
gem "elasticsearch", "~> 7.13.3"

# OmniAuth-based authentication
gem "devise", "~> 4.8.0"
gem "devise-i18n", "~> 1.10.0"
gem "omniauth", "~> 1.9.2"
gem "omniauth-rails_csrf_protection", "~> 0.1.1"
gem "omniauth-cas", "~> 1.1.0", :git => "https://github.com/GUI/omniauth-cas.git", :branch => "rexml", :require => false
gem "omniauth-facebook", "~> 8.0.0", :require => false
gem "omniauth-github", "~> 1.4.0", :require => false
gem "omniauth-gitlab", "~> 2.0.0", :require => false
gem "omniauth-google-oauth2", "~> 0.8.0", :require => false
gem "gitlab_omniauth-ldap", "~> 2.1.0", :require => false

# Authorization
gem "pundit", "~> 2.1.0"

# Views/templates for APIs
gem "rabl", "~> 0.14.0"
gem "jbuilder", "~> 2.9"
gem "csv_builder", "~> 2.1.1"

# Country and state name lookups
gem "countries", "~> 3.1.0"

# For user-inputted YAML.
gem "safe_yaml", "~> 1.0.4", :require => "safe_yaml/load"

# Delayed jobs and background tasks
gem "delayed_job_mongoid", "~> 2.3.0"
gem "daemons", "~> 1.4.0"

# HTML email styling
# nokogiri is a soft-dependency for premailer-rails so we need to explicitly
# include it here.
gem "premailer-rails", "~> 1.11.0"
gem "nokogiri", "~> 1.10"

# Localization in the admin based on the Accept-Language header
gem "http_accept_language", "~> 2.1.1"

# Markdown
gem "kramdown", "~> 2.3.1"
gem "kramdown-parser-gfm", "~> 1.1.0"

# Lucene query parsing for translating into SQL.
gem "lucene_query_parser", :git => "https://github.com/zerowidth/lucene_query_parser.git"

# Thread-safe per-request variables.
gem "request_store", "~> 1.5.0"

# Share i18n data with the admin-ui client-side app.
gem "i18n-js", "~> 3.8.0"

# Log to stdout instead of file
#
# Use master, since v0.0.5 doesn't yet have these fixes to prevent the log file
# from being attempted: https://github.com/heroku/rails_stdout_logging/pull/28
gem "rails_stdout_logging", :git => "https://github.com/heroku/rails_stdout_logging.git"

# Login forms
gem "simple_form", "~> 3.5", ">= 3.5.1"

# Login stylesheets
gem "sass-rails", "~> 6.0.0"
gem "sprockets", "< 4"
gem "bootstrap", "~> 4.5.0", :require => false
gem "font-awesome-rails", "~> 4.7", :require => false

# Table-less models
gem "active_attr", "~> 0.15.0"

# URI parsing
gem "addressable", "~> 2.8.0"

# Public suffix for hostnames.
gem "public_suffix", "~> 4.0.1"

# Patch for CVE-2020-5267 in Rails 4.
gem "legacy-rails-CVE-2020-5267-patch"

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  # Check for security issues on gem dependencies.
  gem "bundler-audit", :require => false

  # Check for application security issues.
  gem "brakeman", :require => false

  # Debug inspecting/printing.
  gem "awesome_print", "~> 1.8"
end
