source "https://rubygems.org"

gem "rails", "~> 4.2.7.1"

# Rails app server
gem "puma", "~> 3.6.2"

# Error notification service (optional)
gem "rollbar", "~> 2.14.0"

# Abort requests that take too long
gem "rack-timeout", "~> 0.4.2"

# For proxying HTTP requests to password-protected places for admins.
gem "rack-proxy", "~> 0.6.0"

# JSON handling
gem "multi_json", "~> 1.12.1"
gem "oj", "~> 2.18.1", :platforms => [:ruby]

# Use Oj for the default Rails to_json calls.
gem "oj_mimic_json", "~> 1.0.1", :platforms => [:ruby]

# SQL escape libraries for Kylin analytics.
gem "sequel", "~> 4.42.1"

# MongoDB
gem "mongoid", "~> 5.1.6"

# Soft-delete
gem "mongoid-paranoia", "~> 2.0.0"

# Versioning for mongoid
gem "mongoid_delorean", "~> 1.3.0"

# Display deeply nested validation errors on embedded documents.
#
# Fork to fix Mongoid 4+ compatibility:
# https://github.com/glooko/mongoid-embedded-errors/pull/6
gem "mongoid-embedded-errors", "~> 2.0.1", :git => "https://github.com/calfzhou/mongoid-embedded-errors.git"

# Data migrations
gem "mongoid_rails_migrations", "~> 1.1.0"

# Rails cache store using mongo.
#
# Use master from git for Rails 4 compatibility.
gem "mongoid-store", :git => "https://github.com/ahoward/mongoid-store.git"

# Database seeding
#
# This branch adds mongoid compatibility:
# https://github.com/mbleigh/seed-fu/pull/80
gem "seed-fu", :git => "https://github.com/GUI/seed-fu.git", :branch => "mongoid"

# Elasticsearch
gem "elasticsearch", "~> 2.0.1"

# OmniAuth-based authentication
gem "devise", "~> 4.2.0"
gem "omniauth", "~> 1.3.2"
gem "omniauth-cas", "~> 1.1.0", :git => "https://github.com/GUI/omniauth-cas.git", :branch => "rexml", :require => false
gem "omniauth-facebook", "~> 4.0.0", :require => false
# Use master for e-mail verification:
# https://github.com/intridea/omniauth-github/pull/48
gem "omniauth-github", :git => "https://github.com/intridea/omniauth-github.git", :require => false
gem "omniauth-google-oauth2", "~> 0.4.1", :require => false
gem "omniauth-ldap", "~> 1.0.5", :require => false
gem "omniauth-twitter", "~> 1.3.0", :require => false

# Authorization
gem "pundit", "~> 1.1.0"

# Generate non-digest assets for i18n content that  the admin-ui component can
# link to (without knowing the cache busted URLs).
gem "non-stupid-digest-assets", "~> 1.0.9"

# Views/templates for APIs
gem "rabl", "~> 0.13.1"
gem "jbuilder", "~> 2.6.0"
gem "csv_builder", "~> 2.1.1"

# Country and state name lookups
gem "countries", "~> 2.0.6"

# For user-inputted YAML.
gem "safe_yaml", "~> 1.0.4", :require => "safe_yaml/load"

# Delayed jobs and background tasks
gem "delayed_job_mongoid", "~> 2.2.0"
gem "daemons", "~> 1.2.4"

# HTML email styling
# nokogiri is a soft-dependency for premailer-rails so we need to explicitly
# include it here.
gem "premailer-rails", "~> 1.9.5"
gem "nokogiri", "~> 1.7.0"

# Localization in the admin based on the Accept-Language header
gem "http_accept_language", "~> 2.1.0"

# Markdown
gem "kramdown", "~> 1.13.2"

# Lucene query parsing for translating into SQL.
gem "lucene_query_parser", :git => "https://github.com/zerowidth/lucene_query_parser.git"

# Thread-safe per-request variables.
gem "request_store", "~> 1.3.2"

# Share i18n data with the admin-ui client-side app.
gem "i18n-js", ">= 3.0.0.rc15"

# Log to stdout instead of file
gem "rails_stdout_logging", "~> 0.0.5", :require => false

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :development, :test do
  # Check for security issues on gem dependencies.
  gem "bundler-audit", :require => false

  # Check for application security issues.
  gem "brakeman", :require => false

  # Debug inspecting/printing.
  gem "awesome_print", "~> 1.7.0"
end

group :development do
  # Deployment
  gem "capistrano", "~> 3.7.1"
  gem "capistrano-rails", "~> 1.2.2"
end
