#!/usr/bin/env ruby

# A script to migrate api keys and user accounts from one server instance to
# another.
#
# This is for the migration of developer.nrel.gov's older and separate API
# Umbrella installation onto api.data.gov's newer one.
#
# Setup compressed double tunnel to directly expose MongoDB on the DB server
# (via NAT server):
# ssh -C -L 9998:$DB_INTERNAL_IP:27017 -N $NAT_IP
#
# Run this script locally to copy data from $CURRENT_SERVER into remote
# destination DB server:
# SOURCE="mongodb://$USERNAME:$PASSWORD@$CURRENT_SERVER/api_umbrella" DEST="mongodb://localhost:9998/api_umbrella" REGISTRATION_SOURCE_PREFIX="name" bundle exec ./script/migrate_users

require "moped"

STDOUT.sync = true
Moped.logger.level = Logger::ERROR

source_session = Moped::Session.connect(ENV["SOURCE"])
dest_session = Moped::Session.connect(ENV["DEST"])

source_collection = source_session[:api_users]
dest_collection = dest_session.with(:safe => true)[:api_users]

existing_users_by_id = {}
existing_users_by_api_key = {}
dest_collection.find.no_timeout.each do |existing|
  existing_users_by_id[existing["_id"]] = existing
  existing_users_by_api_key[existing["api_key"]] = existing
end

source_collection.find.no_timeout.each do |user|
  print "."

  # Mark this user as imported, so we can distinguish those imported users.
  user["imported"] = true
  user["registration_source"] = [ENV["REGISTRATION_SOURCE_PREFIX"], user["registration_source"]].compact.join("_")

  existing = existing_users_by_id[user["_id"]]
  if existing
    if(existing != user)
      if(existing["api_key"] != user["api_key"])
        puts "\nERROR: #{existing["_id"]} ID (#{existing["email"]}) already exists but API keys do not match. Skipping...\nExisting:  #{existing.inspect}\nImporting: #{user.inspect}"
        next
      elsif(existing["email"] != user["email"])
        puts "\nERROR: #{existing["_id"]} ID (#{existing["email"]}) already exists but emails do not match. Skipping...\nExisting:  #{existing.inspect}\nImporting: #{user.inspect}"
        next
      elsif(existing["email"].include?("@internal"))
        puts "\nERROR: #{existing["_id"]} ID (#{existing["email"]}) already exists but is for an internal API key. Skipping...\nExisting:  #{existing.inspect}\nImporting: #{user.inspect}"
        next
      end

      puts "\nUpdating: #{existing["_id"]} ID (#{existing["email"]}) already exists and the records do not match. Updating...\nExisting:  #{existing.inspect}\nImporting: #{user.inspect}"

      begin
        dest_collection.find(:_id => user["_id"]).update(user)
      rescue
        puts "ERROR inserting user: #{user.inspect}"
        raise e
      end
    end

    next
  end

  existing = existing_users_by_api_key[user["api_key"]]
  if(existing)
    if(existing != user)
      puts "\nERROR: #{existing["api_key"]} api key (#{existing["email"]}) already exists and the records do not match:\nExisting:  #{existing.inspect}\nImporting: #{user.inspect}"
    end

    next
  end

  begin
    dest_collection.insert(user)
  rescue => e
    puts "ERROR inserting user: #{user.inspect}"
    raise e
  end
end

puts ""
