#!/bin/bash

# Exit on any errors
set -e

# Clone if new
if [ ! -d $CHECKOUT_DIR ]; then
  git clone $GIT_URL $CHECKOUT_DIR
fi

# Pull the latest down
cd $CHECKOUT_DIR
git checkout $BRANCH
git submodule update --init --recursive
git pull

# Install dependencies
bundle install --path=vendor/bundle

# Make sure the site can compile and pass any tests.
bundle exec rake test

# Deploy ahoy!
bundle exec cap $DEPLOY_ENV deploy
