#!/usr/bin/env bash

set -e -u

source_dir="$(dirname "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")")"

PATH="$source_dir/build/work/test-env/bin:$PATH"

# Ignore certain vendored files for linting.
ignore_files=(
  "configure"
  "templates/etc/perp/kylin/rc.run.mustache"
)

shells=(
  "sh"
  "bash"
)

for shell in "${shells[@]}"; do
  readarray -t shell_files < <(git grep -l "^#\!/bin/$shell")
  readarray -t shell_files < <(git grep -l "^#\!/usr/bin/env $shell")

  if [ "${#shell_files[@]}" != 0 ]; then
    for ignore in "${ignore_files[@]}"; do
      if [ "${#shell_files[@]}" != 0 ]; then
        shell_files=(${shell_files[@]/#$ignore})
      fi
    done

    if [ "${#shell_files[@]}" != 0 ]; then
      echo -n "Linting ($shell): ${shell_files[*]}... "
      shellcheck -s "$shell" "${shell_files[@]}"
      echo "Valid"
    fi
  fi
done
