source "https://rubygems.org"

gem "middleman", "~> 4.2.1"

# Assets
gem "middleman-sprockets", "~> 4.1.0"

# For execjs
gem "mini_racer", "~> 0.1.9"

# Deploy to GitHub Pages
gem "middleman-gh-pages", "~> 0.3.1"

# Markdown
gem "kramdown", "~> 1.13.2"

# Assets
gem "bootstrap-sass", "~> 3.3.7"
gem "font-awesome-sass", "~> 4.7.0"
