source "https://rubygems.org"

gem "middleman", "~> 4.3.0"

# Assets
gem "middleman-sprockets", "~> 4.1.1"

# For execjs
gem "mini_racer", "~> 0.2.4"

# Deploy to GitHub Pages
gem "middleman-gh-pages", "~> 0.3.1"

# Markdown
gem "kramdown", "~> 1.17.0"

# Assets
gem "bootstrap-sass", "~> 3.3.7"
gem "font-awesome-sass", "~> 4.7.0"
