#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

export PATH="$DEV_PATH"
export BUNDLE_GEMFILE="$SOURCE_DIR/Gemfile"
export BUNDLE_APP_CONFIG="$WORK_DIR/tasks/test-deps/bundle/_persist/.bundle"
bundle exec "$@"
